name: Initialize Market Extension Publishing

on: 
  workflow_dispatch:
    inputs:
      productName:
        description: |
          Product Name (as displayed as name on the website), i.e. check Axon Ivy Portal at https://market.axonivy.com/portal#tab-description
        required: true
      productType:
        description: 'Category – choose between Connector (REST/SOAP connection), Utils (little helper), or Demo (demo process, i.e. best practice)'
        required: true
        type: choice
        options:
          - connector
          - utils
          - demo
      version:
        description: 'Ivy version used for development (e.g. 12.0.0)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  initialize-market-extension:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs only on the master branch"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Update name, groupId, artifactId, version, document
        run: |
          productName="${{ github.event.repository.name }}"
          productType="${{ github.event.inputs.productType }}"
          # Remove productType suffix, then replace dashes with dots
          groupId="com.axonivy.$productType.${productName/%-${productType}}"
          groupId="${groupId//-/.}"

          # Perform replacements
          find . -type f -not -path "./.git/*" -not -path "./.github/*" \
            -exec sed -i \
              -e "s|# MY-PRODUCT-NAME|# ${{ github.event.inputs.productName }}|g" \
              -e "s|\"MY-PRODUCT-NAME\"|\"${{ github.event.inputs.productName }}\"|g" \
              -e "s|MY-PRODUCT-NAME|${productName}|g" \
              -e "s|<version>12.0.0-SNAPSHOT</version>|<version>${{ github.event.inputs.version }}-SNAPSHOT</version>|g" \
              -e "s|MY-GROUP-ID|$groupId|g" \
              -e "s|REPO-NAME|${productName}|g" \
              -e "s|<groupId>com.axonivy.market</groupId>|<groupId>$groupId</groupId>|g" {} +

      - name: Replace placeholders in file and folder names
        run: |
          productName="${{ github.event.repository.name }}"

          # Traverse deepest paths first to avoid conflicts
          find . -depth -name "*MY-PRODUCT-NAME*" \
            -exec bash -c 'f="{}"; mv "$f" "$(dirname "$f")/$(basename "$f" | sed "s/MY-PRODUCT-NAME/'"$productName"'/g")"' \;

      - name: Commit changes to master
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rm .github/workflows/initialize-market-extension-publishing.yml || true
          git add .
          git commit -m "Initialize new product: ${{ github.event.inputs.productName }} v${{ github.event.inputs.version }}" || echo "No changes to commit"
          git push origin master